--STUDENTS TABLE
CREATE TABLE STUDENTS (
    STUDENT_ID INT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    COURSE VARCHAR(100) NOT NULL,
    YEAR_OF_STUDY INT,
    EMAIL VARCHAR(150) UNIQUE CHECK (EMAIL LIKE '%_@_%._%')
);


--BOOKS TABLE
CREATE TABLE BOOKS (
    BOOK_ID INT PRIMARY KEY,
    TITLE VARCHAR(200) NOT NULL,
    AUTHOR VARCHAR(150) NOT NULL,
    CATEGORY VARCHAR(100),
    TOTAL_COPIES INT NOT NULL
);


--TRANSACTIONS TABLE
CREATE TABLE TRANSACTIONS (
    TRANSACTION_ID INT PRIMARY KEY,
    BOOK_ID INT,
    STUDENT_ID INT,
    BORROW_DATE DATE NOT NULL,
    RETURN_DATE DATE,
    DUE_DATE DATE NOT NULL,
    FINE_AMOUNT DECIMAL(10,2) DEFAULT 0,

    CONSTRAINT FK_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID),
    CONSTRAINT FK_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID)
);